### ISSUE TITLE
gopoc-mysql报错  

### ISSUE THREAD

**Issue by york-cmd** [SleepingBag945/dddd#1]
<img width="718" alt="image" src="https://github.com/SleepingBag945/dddd/assets/64241747/3d79cb6e-5d66-4fb7-99f8-4c4dff0f4a13">

**Comment by SleepingBag945** [comment]
有详细的主机信息吗，我复现一下

**Comment by york-cmd** [comment]
PORT     STATE SERVICE VERSION
3306/tcp open  mysql   MySQL 5.5.62-log

**Comment by SleepingBag945** [comment]
discord同名 SleepingBag945

**Comment by SleepingBag945** [comment]
参考https://github.com/shadow1ng/fscan/issues/232
不影响扫描，忽视就行。
