### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Cristiano-zzz** [SleepingBag945/dddd#12]
![image](https://github.com/SleepingBag945/dddd/assets/52123616/2ce4b90f-4b4d-4449-abb3-2d74b2f34795)
[FTL] 请检查指纹数据库是否正常。

请问是什么原因

**Comment by SleepingBag945** [comment]
这是缺少配置文件了。

.是dddd二进制文件的目录
.config是配置文件目录
需要确保./config/finger.yaml文件存在。

确认下是否在release中下载config.zip并解压到dddd二进制文件同目录了呢。

**Comment by Cristiano-zzz** [comment]
![image](https://github.com/SleepingBag945/dddd/assets/52123616/b3c5d4a8-5031-4188-8cfa-f0c2c2e74ef4)
这样可以吗？

**Comment by SleepingBag945** [comment]
在这个目录新建一个config文件，将除了dddd64.exe的所有文件拖到config里

**Comment by Cristiano-zzz** [comment]
解决了，太感谢了
