### ISSUE TITLE
Found 229 templates with runtime error&&Could not read nuclei-ignore file:

### ISSUE THREAD

**Issue by uf9n1x** [SleepingBag945/dddd#13]
请问这样报错是为什么？影响使用吗
![图片](https://github.com/SleepingBag945/dddd/assets/84779840/d89632d0-280d-4891-b201-e7874a928974)

**Comment by SleepingBag945** [comment]
这个是找不到nuclei的文件，我没理干净。无影响，下个版本统一改了

**Comment by uf9n1x** [comment]
好的好的，感谢！第二个报错呢？是否有影响？

**Comment by SleepingBag945** [comment]
无影响，下个版本全改掉

**Comment by uf9n1x** [comment]
好的，作者很强，工具好用到爆炸，爱了爱了，加油！！！！
