### ISSUE TITLE
端口数量超出阈值丢弃目标如何处理？

### ISSUE THREAD

**Issue by uf9n1x** [SleepingBag945/dddd#14]
![图片](https://github.com/SleepingBag945/dddd/assets/84779840/dcff7132-d678-4a86-99fb-22ecf7f72c03)

**Comment by SleepingBag945** [comment]
你扫的目标是不是开放了大于300个端口。
一般开放过多就是非正常的机器。
若还是要尝试扫描，可以使用pc参数，将pc调大，大于此目标开放的端口即可。

 -pc int
    	一个IP的端口数量阈值,当一个端口的IP数量超过此数量，此IP将会被抛弃 (default 300)
