### ISSUE TITLE
win下运行报错

### ISSUE THREAD

**Issue by iamHuFei** [SleepingBag945/dddd#16]
![image](https://github.com/SleepingBag945/dddd/assets/88227929/3a72cccd-01f2-49af-884f-9b9b1539932c)

**Comment by SleepingBag945** [comment]
dddd_win
    - config
        - finger.yaml
        - workflow.yaml
        - ...
    - dddd64.exe

目录结构弄成这样。
config文件可以从release下config.zip解压

**Comment by SleepingBag945** [comment]
<img width="515" alt="图片" src="https://github.com/SleepingBag945/dddd/assets/100852628/46752314-3331-4131-97a9-0dedd6b5d2cd">


目录结构弄成这样。
config文件可以从release下config.zip解压

**Comment by iamHuFei** [comment]
soga，感谢
