### ISSUE TITLE
quake调用icp指纹出现问题

### ISSUE THREAD

**Issue by iamHuFei** [SleepingBag945/dddd#21]
quake直接命令行测试显示api错误
![image](https://github.com/SleepingBag945/dddd/assets/88227929/fa916120-95e6-4bbc-a65a-e56efae2db44)
把指纹放入fofa.txt可运行，但是有个问题是导出的url只有ip+端口而非url链接
![image](https://github.com/SleepingBag945/dddd/assets/88227929/7092f4b7-f504-4bc0-887e-173b7bebc9f7)
![image](https://github.com/SleepingBag945/dddd/assets/88227929/c20629d2-4145-4cd9-b721-e8c9eea67480)
由于我个人对go语言不熟，不太清楚是不是我自身的问题，这是我这边quake调用提取资产url即http_load_url（因为我在佬的代码中没找到http_load_url，觉得可能是这个问题）的python版，仅供参考
```
def Quake(icp, finger):
    time.sleep(0.5)
    headers = {
        "X-QuakeToken": "",
        "Content-Type": "application/json"
    }
    # icp ="南京信息工程大学"
    data = {
        "query": f"icp_keywords:\"{icp}\" AND {finger}",
        "start": 0,
        "size": 100,
        "ignore_cache": True,
        "start_time": "2023-06-05 00:00:00",
        "end_time": "2023-12-08 00:00:00"
    }

    # proxies = {"http": "http://127.0.0.1:8080", "https": "https://127.0.0.1:8080"}
    res = requests.post(url="https://quake.360.net/api/v3/search/quake_service", headers=headers, json=data,
                        verify=False)
    res = json.loads(res.text)
    data = res["data"]
    # n = 0
    urls = []
    for i in data:
        url = i["service"]["http"]["http_load_url"][0]
        urls.append(url)
    return urls
```

**Comment by SleepingBag945** [comment]
Quake支持icp_keywords:"xxx"嘛？我这咋不行的

**Comment by SleepingBag945** [comment]
{"code":"u3017","message":"暂不支持该字段查询。[icp_keywords]","data":{},"meta":{}}
![图片](https://github.com/SleepingBag945/dddd/assets/100852628/372736b6-af51-468c-b8d0-a28dac67dc5e)

**Comment by iamHuFei** [comment]
会员语法，需要的话留个wx我发你测试

**Comment by SleepingBag945** [comment]
dicord: SleepingBag945

**Comment by iamHuFei** [comment]
没搜到，我的wx：chatGPT_FEI

**Comment by SleepingBag945** [comment]
去discord搜，不加wx

**Comment by iamHuFei** [comment]
ok

**Comment by iamHuFei** [comment]
记得看discord消息哦

**Comment by SleepingBag945** [comment]
解决了
