### ISSUE TITLE
指纹条数太大索引越界

### ISSUE THREAD

**Issue by Mstce** [SleepingBag945/dddd#22]
当我使用python处理我的指纹yaml内容新增到三万条时 dddd不能他不能正常运行了 提示索引越界
![image](https://github.com/SleepingBag945/dddd/assets/98394372/a9614fec-c8ed-49fb-8432-7af39af7270b)

**Comment by SleepingBag945** [comment]
可以提供一下你的finger.yaml吗。
discord: SleepingBag945

**Comment by Mstce** [comment]
已向你添加好友申请
