### ISSUE TITLE
quake调用ffmc失效

### ISSUE THREAD

**Issue by iamHuFei** [SleepingBag945/dddd#23]
quake只能默认调用99条，能否也加上ffmc呢

**Comment by iamHuFei** [comment]
催更【手动狗头】

**Comment by SleepingBag945** [comment]
忙哇。先鸽几天

**Comment by SleepingBag945** [comment]
我记得更新过-qkmc参数的，Quake 查询资产条数。你试试

**Comment by iamHuFei** [comment]
ok上面问题解决，现在出现个情况，为了节约扫描时间，语法采取多条件会出现无法调用的情况
domain="zju.edu.cn" && after="2023-06-30" && title!="302 Found"可以
domain="zju.edu.cn" && after="2023-06-30" && title!="302 Found" && title!="跨媒体发布平台"这样就不行了
![image](https://github.com/SleepingBag945/dddd/assets/88227929/6719be9c-864a-4cf1-8a48-8abf03832366)

**Comment by SleepingBag945** [comment]
放假回来了。我看看

**Comment by SleepingBag945** [comment]
知道问题了，草率了。fofa不能用url base64。
