### ISSUE TITLE
v1.6.1

### ISSUE THREAD

**Issue by Extautism** [SleepingBag945/dddd#26]
运行报错
[INF] YAML指纹数据: 8343 条
panic: time: missing Location in call to Time.In

goroutine 1 [running]:
time.Time.In(...)
        time/time.go:1146
github.com/projectdiscovery/gologger.(*Logger).Log(0xc0003bf0c0, 0xc00880b740)
        github.com/projectdiscovery/gologger@v1.1.11/gologger.go:102 +0x305
github.com/projectdiscovery/gologger.(*Event).Msgf(0xc00880b740, {0x3498158?, 0x0?}, {0xc000845db8?, 0x0?, 0x0?})
        github.com/projectdiscovery/gologger@v1.1.11/gologger.go:186 +0x65
dddd/common.prepare()
        dddd/common/flag.go:260 +0xfcd
dddd/common.Flag()
        dddd/common/flag.go:359 +0xb2e
main.main()
        ./main.go:22 +0xf

**Comment by Extautism** [comment]
是的

**Comment by SleepingBag945** [comment]
是什么时候下载的release，这行号对不上的。现在重下一次试试。最新的我这没有问题
<img width="1121" alt="图片" src="https://github.com/SleepingBag945/dddd/assets/100852628/26e1ddc2-d993-4825-81b9-be2658193b58">

**Comment by Extautism** [comment]
好了好了 新下载的没问题了

**Comment by SleepingBag945** [comment]
感谢您的反馈
