### ISSUE TITLE
漏洞扫描存在资产遗漏问题

### ISSUE THREAD

**Issue by M85081aureenGresham** [SleepingBag945/dddd#37]
每一遍结果都不一样，指纹识别出的东西没有进行检测，单独对遗漏的进行探测可以成功

**Comment by M85081aureenGresham** [comment]
![image](https://github.com/SleepingBag945/dddd/assets/139992049/9da05ccb-999c-440b-bc6e-5b738f175926)
存在问题，但是并没有扫描出漏洞，
![image](https://github.com/SleepingBag945/dddd/assets/139992049/2c2e2f12-8661-4014-ba23-7725be95d2cf)
这是单独测试的结果

**Comment by M85081aureenGresham** [comment]
我看了下日志，发现它没有识别出nacos的指纹。。。。。。

**Comment by SleepingBag945** [comment]
线程调小试试，可能触发到拥塞控制或者设备了

**Comment by M85081aureenGresham** [comment]
> 线程调小试试，可能触发到拥塞控制或者设备了

默认的线程

**Comment by SleepingBag945** [comment]
继续调小

**Comment by M85081aureenGresham** [comment]
ok
