### ISSUE TITLE
一直卡在主动指纹探测可能是什么原因

### ISSUE THREAD

**Issue by zyyszds** [SleepingBag945/dddd#43]
师傅，这个命令行一直卡在这个页面是为啥
![image](https://github.com/SleepingBag945/dddd/assets/86825028/ea9d209a-73b1-4333-856f-c5d216cf4bf8)

**Comment by SleepingBag945** [comment]
这是在跑，但没探测到主动指纹所以不会显示。如果觉得慢可以加-nd参数。
