### ISSUE TITLE
nuclei引擎无结果

### ISSUE THREAD

**Issue by fjjcxy** [SleepingBag945/dddd#48]
![微信图片_20240328153636](https://github.com/SleepingBag945/dddd/assets/88481324/822abdb9-fb43-4f8f-9c32-ac072ac2bf11)

想请问一下，这个nuclei引擎无结果是因为没扫出漏洞是吗

**Comment by SleepingBag945** [comment]
是的，没有漏洞

**Comment by SleepingBag945** [comment]
是的，没有扫出漏洞
