### ISSUE TITLE
指纹匹配漏报问题

### ISSUE THREAD

**Issue by fengbenjianmo** [SleepingBag945/dddd#52]
dddd在匹配资产指纹的时候，貌似只会从第一个请求匹配，而指纹定义是以目标的http 200正文为准，所以就导致了指纹和匹配响应的数据包不对等，比如某金蝶eas：http://test.com，第一个响应是302，第二个响应也是302， 直到第三个响应才是应用正文，200状态码，而dddd只会从第一个302的响应去匹配指纹，从而导致漏报。
如下dddd对金蝶eas的指纹定义：
![image](https://github.com/SleepingBag945/dddd/assets/53716731/d94037e1-0be3-4bea-a083-d17fa41d468b)
用一个存在漏洞的金蝶eas目标测试，并不能识别到金蝶eas：
![image](https://github.com/SleepingBag945/dddd/assets/53716731/af84bf58-6cf1-489b-aeb5-4720a809d6c6)
以这个302响应的特征，加入到金蝶eas的指纹规则后，可以识别，并检出漏洞：
![image](https://github.com/SleepingBag945/dddd/assets/53716731/636df9ad-7e6a-43d6-9c20-b754e6a859a1)
![image](https://github.com/SleepingBag945/dddd/assets/53716731/066c8c00-00c8-40e0-a46d-dc3c0c20f0f1)

**Comment by SleepingBag945** [comment]
okok,马上更新
