### ISSUE TITLE
指纹匹配问题

### ISSUE THREAD

**Issue by brucelsone** [SleepingBag945/dddd#59]
自己加的指纹识别不到
<img width="727" alt="image" src="https://github.com/SleepingBag945/dddd/assets/101378596/985012f2-cff7-422a-be02-506a058c5d96">
<img width="947" alt="image" src="https://github.com/SleepingBag945/dddd/assets/101378596/bce2257c-b640-44b3-aeae-e11c21e76c45">

**Comment by SleepingBag945** [comment]
不在根下可以考虑其他的指纹吗
