### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by brucelsone** [SleepingBag945/dddd#62]
mac arm版本运行报错
dddd为最新版本
<img width="762" alt="image" src="https://github.com/SleepingBag945/dddd/assets/101378596/55c6998a-6c0b-43ca-bfc8-edf0f3e333d1">

**Comment by yooreea** [comment]
俺也遇到这个问题了，先用2.0吧/**捂脸**/

**Comment by SleepingBag945** [comment]
师傅有自行编辑过finger.yaml吗

**Comment by brucelsone** [comment]
在finger.yaml里添加了一些指纹特征

**Comment by SleepingBag945** [comment]
校验下指纹，估计是指纹的问题
