### ISSUE TITLE
go build报错

### ISSUE THREAD

**Issue by Jim2g** [SleepingBag945/dddd#7]
师傅为啥go build 报错这个呢
![image](https://github.com/SleepingBag945/dddd/assets/52034185/81d3dbf6-8e59-436a-b971-db6fbdafb0c9)

**Comment by SleepingBag945** [comment]
试试拉新的dddd，不行的话直接改go.sum下的checksum，把他弄得和下载的一样就行了

**Comment by Jim2g** [comment]
好的
