### ISSUE TITLE
启动nuclei时报错

### ISSUE THREAD

**Issue by sansaniii2023** [SleepingBag945/dddd#8]
[ERR] Could not read nuclei-ignore file: open C:\Users\Administrator\.config\nuclei\.nuclei-ignore: The system cannot find the file specified.
请问这是要放一个忽略ssl报错的文件进去吗？

**Comment by SleepingBag945** [comment]
忽略就行嘞，不依赖此文件，这个不影响。下个版本把这个err嘎掉

**Comment by sansaniii2023** [comment]
我知道了，，是要先运行一次nuclei，要初始化一下，会自动生成这个文件
