### ISSUE TITLE
提个改动

### ISSUE THREAD

**Issue by Layjb** [SleepingBag945/dddd#9]
-fofa后，-t参数的fofa语句“需要/转译，貌似也不支持多语句，打个比方：
-fofa -t app=\"泛微-EOffice\" && city=\"Shanghai\" 只会匹配到app=\"泛微-EOffice\"
(\"泛微-EOffice\" && city=\"Shanghai\")会报错zsh: bad pattern: (app="泛微-EOffice"

**Comment by SleepingBag945** [comment]
多语句可以写到target.txt，写进target.txt的不需要转义，直接原样写,./dddd -t target.txt -fofa
命令行转义问题，可以用单引号
./dddd -t 'app="泛微-EOffice" && city="Shanghai"' -fofa

**Comment by Layjb** [comment]
明白，感谢
